name: API Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository Structure
        run: ls -R  # Debugging step: List all files in repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run API Tests
        run: |
          cd RestAssuredTest  # Ensure mvn test runs inside the correct folder
          mvn test || echo "Tests failed, continuing to generate reports..."

      - name: Generate Test Report
        if: always()
        run: |
          cd RestAssuredTest  # Ensure the report is generated in the right folder
          mvn surefire-report:report

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports
          path: RestAssuredTest/target/surefire-reports  # Corrected path
